---
:repos:
  puppet:
    :ref: origin/2.7.x
    :repo: git://github.com/puppetlabs/puppet.git
  facter:
    :ref: origin/1.6.x
    :repo: git://github.com/puppetlabs/facter.git
  sys:
    :ref: origin/master
    :repo: git://github.com/puppetlabs/puppet-win32-ruby.git
